In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## LOAD THE DATASETS AND LIBRARIES

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import warnings
warnings.filterwarnings('ignore')

In [7]:
from sklearn.datasets import load_digits
data = load_digits()

dir(data)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [8]:
df = pd.DataFrame(data.data)
df['target'] = data.target

df.sample(10)

0    1     2     3     4     5     6    7    8     9  ...   55   56  \
478   0.0  0.0   4.0  10.0  13.0   3.0   0.0  0.0  0.0   4.0  ...  0.0  0.0   
927   0.0  2.0  13.0  16.0  10.0   0.0   0.0  0.0  0.0  12.0  ...  0.0  0.0   
224   0.0  0.0   0.0  10.0  12.0   3.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   
288   0.0  0.0   6.0   8.0   8.0  13.0   3.0  0.0  0.0   1.0  ...  0.0  0.0   
313   0.0  2.0  11.0  16.0  12.0   1.0   0.0  0.0  0.0   9.0  ...  0.0  0.0   
1072  0.0  0.0   5.0  10.0  11.0  13.0  12.0  0.0  0.0   2.0  ...  0.0  0.0   
345   0.0  0.0  12.0  16.0  16.0  13.0   1.0  0.0  0.0   4.0  ...  0.0  0.0   
209   0.0  0.0   0.0  14.0   7.0   0.0   0.0  0.0  0.0   1.0  ...  0.0  0.0   
820   0.0  0.0   3.0  15.0  16.0  15.0   1.0  0.0  0.0   0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0   0.0  ...  0.0  0.0   

       57    58    59    60    61    62   63  target  
478   0.0   4.0  12.0  14.0  11.0   2.0  0.0       9  
927   1.0  13.0  16.0  16.0  16.0  16.0  3.0       2  
224   0.0   2.0  10.0  14.0  13.0   4.0  0.0       8  
288   0.0   9.0  15.0   8.0   0.0   0.0  0.0       5  
313   2.0  15.0  16.0  16.0  13.0  16.0  1.0       2  
1072  0.0   7.0  11.0   0.0   0.0   0.0  0.0       7  
345   0.0  12.0  16.0  16.0   9.0   0.0  0.0       3  
209   0.0   2.0  10.0  13.0   6.0   0.0  0.0       0  
820   0.0   4.0  14.0   1.0   0.0   0.0  0.0       7  
2     0.0   0.0   3.0  11.0  16.0   9.0  0.0       2  

[10 rows x 65 columns]

In [9]:
X = df.drop(columns = ['target'])
y = df['target']

X.shape, y.shape

((1797, 64), (1797,))

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

X_train.shape, y_train.shape

((1257, 64), (1257,))

In [16]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9648148148148148

In [17]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [18]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

This method of checking which model is better is too naive, and it is not a best practical method to know it. Because the dataset is not split correctly

In [19]:
from sklearn.model_selection import KFold

kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [21]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

# this is how kfold works, where you can see the whole dataset is split in a balanced way, and given all the dataset in train and test split

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [26]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

# This function makes it easy to return the scores of all the comparing models

In [23]:
get_score(lr, X_train, X_test, y_train, y_test)

0.9648148148148148

In [24]:
get_score(svm, X_train, X_test, y_train, y_test)

0.987037037037037

In [25]:
get_score(rf, X_train, X_test, y_train, y_test)

0.975925925925926

In [27]:
# The stratified version of KFold, this devides the target column in uniform way to get the balaced data in all the folds

from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits = 3)

In [33]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index] 
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    print(get_score(lr, X_train, X_test, y_train, y_test))
    print(get_score(svm, X_train, X_test, y_train, y_test))
    print(get_score(rf, X_train, X_test, y_train, y_test))
    

0.9215358931552587
0.9649415692821369
0.9432387312186978
0.9415692821368948
0.9799666110183639
0.9532554257095158
0.9165275459098498
0.9649415692821369
0.9332220367278798


In [34]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index] 
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    scores_l.append(get_score(lr, X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(svm, X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(rf, X_train, X_test, y_train, y_test))
    

In [44]:
scores_l
np.average(scores_l)

0.9265442404006677

In [45]:
scores_svm
np.average(scores_svm)

# This is the best model that we got

0.9699499165275459

In [46]:
scores_rf
np.average(scores_rf)

# lets take the average and get which model is the best

0.9393433500278241

In [39]:
# Instead of creating a different funcion as above, we have a built in library

from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(), X, y)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [41]:
cross_val_score(svm, X, y)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [43]:
cross_val_score(rf, X, y)

array([0.93055556, 0.90277778, 0.95821727, 0.95543175, 0.93036212])

In [48]:
# we can do directly like this also

scores1 = cross_val_score(LogisticRegression(), X, y, cv = 10)
np.average(scores1)

0.928193668528864

In [51]:
scores2 = cross_val_score(svm, X, y, cv = 10)
np.average(scores2)

# The best model

0.9699503414028554

In [50]:
scores3 = cross_val_score(rf, X, y, cv = 10)
np.average(scores3)

0.9487988826815641