In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import pandas as pd
import numpy as np
import math
from sklearn import linear_model

In [3]:
df = pd.read_csv("/kaggle/input/homeprices-csv/homeprices.csv")

In [4]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']], df.price)

LinearRegression()

In [7]:
reg.coef_

array([135.78767123])

In [8]:
reg.intercept_

180616.43835616432

## SAVE THE MODEL USING PICKLE

In [9]:
import pickle

In [11]:
# save the python object

with open('model_pickle', 'wb') as f:
    pickle.dump(reg, f)

In [13]:
with open('model_pickle', 'rb') as f:
    model = pickle.load(f)

In [14]:
model.coef_

array([135.78767123])

In [15]:
model.intercept_

180616.43835616432

In [19]:
model.predict(np.array([5000]).reshape(1, -1))

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

## SAVE THE MODEL USING SKLEARN'S JOBLIB
if the model consist of large numpy array, this is the go to option

In [21]:
# from sklearn.externals import joblib
import joblib

In [22]:
joblib.dump(model, 'model_jbolib')

['model_jbolib']

In [23]:
mj = joblib.load('model_jbolib')

In [25]:
mj.coef_

# Getting same coefficient

array([135.78767123])